Ceramic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bicycle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]


if settings.DEBUG:
   urlpatterns.append(path('static/<path:path>', never_cache(serve)))
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
   path('', views.loginUser, name='login'),
   path('keys', views.key.as_view(), name="key"),
   path('requisites', views.req.as_view(), name="req"),
   path('logout', views.logout.as_view(), name="logout"),
   path('registration', views.createUser.as_view(), name="createUser"),
   path('validateKey', views.validateKey, name='validateKey'),
   path('password_email/<str:sign>', views.password_email, name='password_email'),
   path('password_email_form', views.password_email_form, name='password_email_form'),
   path('checks', views.checks.as_view(), name="checks"),
   path('help', views.Help.as_view(), name="help"),
   path('profile', views.profile.as_view(), name="profile"),
   path('requisites_add', views.requisites_add.as_view(), name="requisites_add"),
   path('requisites_edit/<int:pk>', views.ChangeRequisites.as_view(), name="ChangeRequisites"),
   path('changePass', views.changePass.as_view(), name="changePass"),
   path('editProfile/<int:pk>', views.ChangeUser.as_view(), name="editProfile"),
]

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from datetime import datetime

from .models import AdvUser, keys, helpMessage, requisites, checks


class RegisterUserForm(forms.ModelForm):
    key = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField()

    def clean_password1(self):
        password = self.cleaned_data['password']
        if password:
            password_validation.validate_password(password)
        return password

    def clean(self):
        super().clean()
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        num = self.cleaned_data['key']
        errors = {}
        if keys.objects.filter(number=num, owner='Отсутствует').exists():
            pass
        else:
            errors['key'] = ValidationError(
                'Несуществующий ключ', code='key_errors'
            )
        if password and password2 and password != password2:
            errors['password2'] = ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )
        if errors != '':
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.date = datetime.now()
        user.email = user.username
        key = keys.objects.get(number=user.key, owner='Отсутствует')
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            key.owner = user
            key.save()
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'password', 'password2', 'first_name', 'key')


class loginForm(forms.Form):
    key = forms.CharField(required=False)
    username = forms.EmailField(required=False)
    password = forms.PasswordInput()

    class Meta:
        fields = ('username', 'password', 'key')


class help_form(forms.ModelForm):
    inv = forms.FileField()

    class Meta:
        model = helpMessage
        fields = '__all__'


class add_req_form(forms.ModelForm):
    class Meta:
        model = requisites
        fields = ('org', 'inn', 'kpp', 'company', 'address', 'contacts', 'email', 'phone',
                  'docs', 'bank', 'checking', 'bic', 'checkingCo', 'ogrn', 'type')


class UploadFileForm(forms.ModelForm):
    pk = forms.CharField(required=False)

    class Meta:
        model = checks
        fields = ('pay', 'pk')


class edit_user_form(forms.ModelForm):
    class Meta:
        model = AdvUser
        fields = ('email', 'first_name', 'time', 'phone')

main/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView, PasswordChangeView
from datetime import datetime

from django.core.exceptions import ValidationError
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, TemplateView, UpdateView
from . import forms, models, utilities


def loginUser(request):
    if request.user.is_authenticated:
        return redirect('/keys')
    else:
        context = {'text': 'Войти по ключу', 'key_display': 'none', 'email_display': 'block'}
        if request.method == "POST":
            username = request.POST['username']
            key = request.POST['key']
            password = request.POST['password']

            if key != '':
                context = {'text': 'Войти по email', 'key_display': 'block', 'email_display': 'none'}
                try:
                    key = models.keys.objects.filter(number=key)
                except key.exists():
                    key = models.keys.objects.get(number=key)
                    userBd = models.AdvUser.objects.get(username=key.owner)
                    success = authenticate(username=userBd.username, password=password)
                    if success is None:
                        context['password'] = 'Неверный пароль'
                    else:
                        login(request, success)
                        return redirect('/keys')
                else:
                    context['key'] = 'Несуществующий ключ'
            elif username != '':
                context = {'text': 'Войти по ключу', 'key_display': 'none', 'email_display': 'block'}
                if models.AdvUser.objects.filter(Q(username=username) | Q(email=username)).exists():
                    AdvUser = models.AdvUser.objects.get(Q(username=username) | Q(email=username))
                    success = authenticate(username=AdvUser.username, password=password)
                    if success is None:
                        context['password'] = 'Неверный пароль'
                    else:
                        login(request, success)
                        return redirect('/keys')
                else:
                    context['password'] = 'Неверный пароль'
            else:
                context['username'] = 'Обязательное поле'
                context['key'] = 'Обязательное поле'
        return render(request, 'user/login.html', context)


class logout(LoginRequiredMixin, LogoutView):
    template_name = 'user/logout.html'
    login_url = '/'
    next_page = '/'


class createUser(CreateView):
    model = models.AdvUser
    template_name = 'user/createUser.html'
    form_class = forms.RegisterUserForm
    success_url = '/'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/keys')
        else:
            return render(request, 'user/createUser.html')


class key(LoginRequiredMixin, TemplateView):
    template_name = 'pages/keys.html'
    login_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_keys'] = models.keys.objects.filter(owner=self.request.user.username)
        context['tariffs'] = models.tariffs.objects.all()
        current_time = datetime.now()
        day = current_time.strftime("%d")
        month = int(current_time.strftime("%m")) + 1
        if month // 10 == 0:
            month = f'0{month}'
        year = current_time.strftime("%Y")
        context['first_date'] = f'{day}.{month}.{year}'
        return context

    def post(self, request, *args, **kwargs):
        pk = request.POST['pk']
        name = request.POST['name']
        if name != '':
            keysBd = models.keys.objects.get(pk=pk)
            keysBd.name = name
            keysBd.save()
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)


class req(LoginRequiredMixin, TemplateView):
    template_name = 'pages/req.html'
    login_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_req'] = models.requisites.objects.filter(owner=self.request.user.username)
        return context


class requisites_add(LoginRequiredMixin, CreateView):
    template_name = 'pages/req_add.html'
    success_url = '/requisites_add'
    form_class = forms.add_req_form
    login_url = '/'

    def post(self, request, *args, **kwargs):
        context = {'display': 'none'}
        form = forms.add_req_form(request.POST)
        if form.is_valid():
            context['display'] = 'block'
            instance = form.save(commit=False)
            instance.owner = self.request.user
            if models.requisites.objects.filter(owner=request.user.username).exists():
                instance.type = 'Дополнительный'
            else:
                instance.type = 'Основной'
            instance.save()
        return render(self.request, 'pages/req_add.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['display'] = 'none'
        return context


class ChangeRequisites(LoginRequiredMixin, UpdateView):
    model = models.requisites
    template_name = 'pages/req_edit.html'
    form_class = forms.add_req_form
    success_url = '/requisites'
    login_url = '/'
    pk_url_kwarg = id

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        pk = self.kwargs.get('pk')
        return get_object_or_404(queryset, pk=pk, owner=self.request.user.username)


def validateKey(request):
    context = {}
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.method == 'GET':
            typeQ = request.GET.get('type')
            if typeQ == '1':
                num = request.GET.get('key')
                if models.keys.objects.filter(number=num, owner='Отсутствует').exists():
                    context['success'] = 1
                else:
                    context['success'] = 0
            elif typeQ == '0':
                num = request.GET.get('key')
                check = request.GET.get('check')
                if models.keys.objects.filter(number=num, checkNum=check, owner='Отсутствует').exists():
                    kye = models.keys.objects.get(number=num, checkNum=check)
                    kye.owner = request.user
                    kye.save()
                    context['success'] = 1
                else:
                    context['success'] = 0
            elif typeQ == '2':
                delKeys = request.GET.get('delKeys')
                delKeys = delKeys.split(';')
                context['success'] = delKeys
                for dels in delKeys:
                    context['success'] = dels
                    if dels != '':
                        if models.keys.objects.filter(number=dels).exists():
                            kye = models.keys.objects.get(number=dels)
                            user = models.AdvUser.objects.get(pk=6)
                            kye.owner = user
                            kye.save()
                context['success'] = 1
    return render(request, 'user/validateKey.html', context)


def password_email_form(request):
    if request.user.is_authenticated:
        return redirect('/keys')
    else:
        context = {'display': 'none'}
        if request.method == "POST":
            username = request.POST['username']
            if models.AdvUser.objects.filter(Q(username=username) | Q(email=username)).exists():
                user = models.AdvUser.objects.get(Q(username=username) | Q(email=username))
                utilities.send_password_notification(user)
                context['mail'] = "Проверьте почту"
                context['display'] = 'block'
            else:
                context['errors'] = "Введен неверный логин"
        return render(request, 'user/password_email_form.html', context)


def password_email(request, sign):
    username = utilities.signer.unsign(sign)
    user = get_object_or_404(models.AdvUser, username=username)
    password = utilities.generate_password()
    user.set_password(password)
    user.save()
    context = {'user': username, 'password': password}
    return render(request, 'user/password_change_email.html', context)


class checks(LoginRequiredMixin, CreateView):
    model = models.checks
    form_class = forms.UploadFileForm
    template_name = 'pages/checks.html'
    login_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_checks'] = models.checks.objects.filter(owner=self.request.user.username)
        return context

    def post(self, request, *args, **kwargs):
        context = {'success': 0, 'list_checks': models.checks.objects.filter(owner=request.user.username)}
        form = forms.UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            if models.checks.objects.filter(pk=request.POST['pk'], owner=request.user.username).exists():
                check = models.checks.objects.get(pk=request.POST['pk'], owner=request.user.username)
                check.pay = request.FILES['pay']
                check.save()
            context['success'] = 1

        return render(request, 'pages/checks.html', context)


class Help(LoginRequiredMixin, CreateView):
    template_name = 'pages/help.html'
    success_url = '/help'
    form_class = forms.help_form
    login_url = '/'

    def post(self, request, *args, **kwargs):
        context = {'display': 'none'}
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = self.request.FILES.getlist('inv')
        if form.is_valid():

main/templates/pages/checks.html
{% extends "basic.html" %}
{% load static%}
{% block content %}
<div class="center clearfix">
    <nav class="page_left">
        <a href="{% url 'main:key' %}" class="nav_item clearfix">
            <div class="nav_item_img img_key"></div>
            <div class="nav_item_name">Ключи</div>
        </a>
        <a href="{% url 'main:req' %}" class="nav_item clearfix">
            <div class="nav_item_img img_req"></div>
            <div class="nav_item_name">Реквизиты</div>
        </a>
        <a href="{% url 'main:checks' %}" class="nav_item clearfix nav_item--active">
            <div class="nav_item_img img_rubl"></div>
            <div class="nav_item_name">Счета</div>
        </a>
        <a href="{% url 'main:help' %}" class="nav_item clearfix">
            <div class="nav_item_img img_help"></div>
            <div class="nav_item_name">Помощь</div>
        </a>
        <a href="{% url 'main:profile' %}" class="nav_item clearfix">
            <div class="nav_item_img img_profile"></div>
            <div class="nav_item_name">Профиль</div>
        </a>
        <a href="{% url 'main:logout' %}" class="nav_item clearfix">
            <div class="nav_item_img img_logout"></div>
            <div class="nav_item_name">Выйти</div>
        </a>
    </nav>
    <div class="page_right">
        <section class="section_page" data-id="3" style="display: block;">
            <a href="//ru.ceramic3d.com/" target="_blank">
                <img class="page_logo" src="{% static 'media/logo.png' %}" alt="logo">
            </a>
            <div class="clear"></div>
            <h1 class="page_title">Счета</h1>
            {% if not list_checks %}
                <p class="empty">Пока нет одного счета</p>
            {% else %}
            <div class="mainTable">
                <div class="tableAccountsFirst clearfix">
                    <div class="tableCell">№ п/п</div>
                    <div class="tableCell">№ счета</div>
                    <div class="tableCell">Дата счета</div>
                    <div class="tableCell">Сумма счета</div>
                    <div class="tableCell">Статус</div>
                    <div class="tableCell">Скачать счет</div>
                    <div class="tableCell">Загрузить платежное поручение</div>
                    <div class="tableCell">Скачать УПД</div>
                </div>
                {% for checks in list_checks %}
                <div class="tableAccountsSecond clearfix">
                    <div class="tableCell">{{forloop.counter}}</div>
                    <div class="tableCell">{{checks.num}}</div>
                    <div class="tableCell">{{checks.date}}</div>
                    <div class="tableCell" data-type="summ_js">{{checks.sum}}</div>
                    <div class="tableCell">{{checks.status}}</div>
                    {% if checks.docs != '' %}
                        <a target="blank" href="{{checks.docs}}" class="tableCell tabelCellArrow"></a>
                    {%endif%}
                    {% if checks.pay != '' %}
                    <div class="tabelCellUnion_parent">
                        <form method="post" data-form="{{checks.pk}}" enctype="multipart/form-data">
                            <input type="hidden" name="pk" value="{{checks.pk}}">
                            <input type="file" name="pay" class="pay_hide">
                            {% csrf_token %}
                        </form>
                        <div class="tableCell tabelCellUnion"></div>
                        {% if checks.pay == '' %}
                        <div class="tabelCellUnion_text">Файл не выбран</div>
                        {% else %}
                        <a target="blank" href="{{checks.pay}}" class="tabelCellUnion_text">
                            Файл добавлен.
                            <div>Скачать</div>
                        </a>
                        {% endif %}
                    </div>
                    {%endif%}
                    {% if checks.upd != '' %}
                    <a target="blank" href="{{checks.upd}}" class="tableCell tabelCellArrow"></a>
                    {%endif%}
                </div>
                {% endfor %}
            {%endif%}
            </div>
        </section>
    </div>
</div>
{% endblock %}

main/templates/pages/help.html
{% extends "basic.html" %}
{% load static%}
{% block content %}
<div class="dark_errors" style="display:{{display}}">
    <div class="errors_container help_mess">
        <div class="errors_container_titles clearfix">
            <div class="errors_container_title">Ceramic 3D</div>
            <div class="errors_container_cross"></div>
        </div>
        <div class="sucsess clearfix">
            <div class="sucsess_text help_mess_text">Спасибо, ваша заявка принята. Мы свяжемся с вами в ближайшее время.</div>
            <div class="sucsess_icon"></div>
        </div>
    </div>
</div>
<div class="center clearfix">
    <nav class="page_left">
        <a href="{% url 'main:key' %}" class="nav_item clearfix">
            <div class="nav_item_img img_key"></div>
            <div class="nav_item_name">Ключи</div>
        </a>
        <a href="{% url 'main:req' %}" class="nav_item clearfix">
            <div class="nav_item_img img_req"></div>
            <div class="nav_item_name">Реквизиты</div>
        </a>
        <a href="{% url 'main:checks' %}" class="nav_item clearfix">
            <div class="nav_item_img img_rubl"></div>
            <div class="nav_item_name">Счета</div>
        </a>
        <a href="{% url 'main:help' %}" class="nav_item clearfix nav_item--active">
            <div class="nav_item_img img_help"></div>
            <div class="nav_item_name">Помощь</div>
        </a>
        <a href="{% url 'main:profile' %}"  class="nav_item clearfix">
            <div class="nav_item_img img_profile"></div>
            <div class="nav_item_name">Профиль</div>
        </a>
        <a href="{% url 'main:logout' %}" class="nav_item clearfix">
            <div class="nav_item_img img_logout"></div>
            <div class="nav_item_name">Выйти</div>
        </a>
    </nav>
    <div class="page_right">
        <section class="section_page">
            <a href="//ru.ceramic3d.com/" target="_blank">
                <img class="page_logo" src="{% static 'media/logo.png' %}" alt="logo">
            </a>
            <div class="clear"></div>
            <h1 class="page_title">Помощь</h1>
            <form method="POST" class="mainMenu" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mailButts clearfix">
                    <input type="text" name="title" class="main_input" placeholder="Тема письма">
                    <div class="star">*</div>
                </div>
                <div class="clear"></div>
                <div class="contactMail">
                    <div>Контактная почта</div>
                    <div class="clear"></div>
                    <div>Мы ответим на вашу контактную почту. Изменить почту можно
                        <a href="{% url 'main:profile' %}">в профиле</a>
                    или в форме внизу</div>
                </div>
                <label class="contactMailIn">
                    <input type="text" placeholder="ij.ceram8ic3d@gmail.com" name="email" class="contactMailInput" value="{{user.email}}">
                    <div class="cross_input"></div>
                </label>
                <div class="mailQuestion">
                    <div>Ваш вопрос</div>
                    <div>Постарайтесь описать детали: если вопрос о конкретных аккаунтах или кампаниях, укажите их ID</div>
                    <div>
                        <textarea placeholder="Введите вопрос" name="question"></textarea>
                    </div>
                </div>
                <div class="investments">
                    <div class="investmentsUp">Вложения</div>
                    <div class="investmentsUp">-</div>
                    <div class="investmentsUp">Необязательно</div>
                </div>
                <div class="clear"></div>
                <div class="investmentsLittle">
                    <div>Можно добавить до 10 файлов. Максимальный размер одного файла - 20 Мбайт.</div>
                    <div>Поддерживаем основные форматы изображений и документов.</div>
                </div>
                <div class="clear"></div>
                <div class="inputFile">
                    <div>Прикрепить файл</div>
                    <input type="file" placeholder="Прикрепить файл" name="inv" id="file_help" multiple>
                </div>
                <p class="errors_file">Фаил не выбран</p>
                <div class="kyesBut">
                    <input type="submit" class="kyesButBut kyesButButBlue" value="Отправить">
                </div>
            </form>
        </section>
    </div>
</div>
{% endblock %}

main/templates/pages/profile.html
{% extends "basic.html" %}
{% load static%}
{% block content %}
<div class="center clearfix">
    <nav class="page_left">
        <a href="{% url 'main:key' %}" class="nav_item clearfix">
            <div class="nav_item_img img_key"></div>
            <div class="nav_item_name">Ключи</div>
        </a>
        <a href="{% url 'main:req' %}" class="nav_item clearfix">
            <div class="nav_item_img img_req"></div>
            <div class="nav_item_name">Реквизиты</div>
        </a>
        <a href="{% url 'main:checks' %}" class="nav_item clearfix">
            <div class="nav_item_img img_rubl"></div>
            <div class="nav_item_name">Счета</div>
        </a>
        <a href="{% url 'main:help' %}" class="nav_item clearfix">
            <div class="nav_item_img img_help"></div>
            <div class="nav_item_name">Помощь</div>
        </a>
        <a href="{% url 'main:profile' %}"  class="nav_item clearfix nav_item--active">
            <div class="nav_item_img img_profile"></div>
            <div class="nav_item_name">Профиль</div>
        </a>
        <a href="{% url 'main:logout' %}" class="nav_item clearfix">
            <div class="nav_item_img img_logout"></div>
            <div class="nav_item_name">Выйти</div>
        </a>
    </nav>
    <div class="page_right">
        <section class="section_page">
            <a href="//ru.ceramic3d.com/" target="_blank">
                <img class="page_logo" src="{% static 'media/logo.png' %}" alt="logo">
            </a>
            <div class="clear"></div>
            <h1 class="page_title">Профиль</h1>
            <div class="profile">
                    <a href="{% url 'main:profile' %}" class="profileA profileA--active">Основное</a>
                    <a href="{% url 'main:changePass' %}" class="profileA">Смена пароля</a>
            </div>
            <div class="clear"></div>
            <div class="mainProfile">
                <div class="leftMail">Контактная почта</div>
                <div class="centerMail">
                    <div>{{user.email}}</div>
                    <div>На этот адрес приходят важные уведомления, ответы тех. поддержки и платежные документы</div>
                </div>
            </div>
            <div class="clear"></div>
            <div class="mainProfileThree">
                <div class="leftMail">Имя</div>
                <div class="centerMail">
                    <div>{{user.first_name}}</div>
                </div>
            </div>
            <div class="clear"></div>
            <div class="mainProfileFour">
                <div class="leftMail">Номер телефона</div>
                <div class="centerMail" id="phone">
                    <div>{{user.phone}}</div>
                </div>
            </div>
            <div class="clear"></div>
            <div class="mainProfileSix">
                <div class="leftMail">Часовой пояс</div>
                <div class="centerMail">
                    <div>{{user.time}}</div>
                </div>
            </div>
            <div class="clear"></div>
            <div class="kyesBut">
                <a href="{% url 'main:editProfile' pk=user.pk %}" type="submit" class="kyesButBut kyesButButBlue marg" >изменить данные</a>
            </div>
        </section>
    </div>
</div>
{% endblock %}

main/templates/pages/req.html
{% extends "basic.html" %}
{% load static%}
{% block content %}
<div class="center clearfix">
    <nav class="page_left">
        <a href="{% url 'main:key' %}" class="nav_item clearfix">
            <div class="nav_item_img img_key"></div>
            <div class="nav_item_name">Ключи</div>
        </a>
        <a href="{% url 'main:req' %}" class="nav_item clearfix nav_item--active">
            <div class="nav_item_img img_req"></div>
            <div class="nav_item_name">Реквизиты</div>
        </a>
        <a href="{% url 'main:checks' %}" class="nav_item clearfix">
            <div class="nav_item_img img_rubl"></div>
            <div class="nav_item_name">Счета</div>
        </a>
        <a href="{% url 'main:help' %}" class="nav_item clearfix">
            <div class="nav_item_img img_help"></div>
            <div class="nav_item_name">Помощь</div>
        </a>
        <a href="{% url 'main:profile' %}"  class="nav_item clearfix">
            <div class="nav_item_img img_profile"></div>
            <div class="nav_item_name">Профиль</div>
        </a>
        <a href="{% url 'main:logout' %}" class="nav_item clearfix">
            <div class="nav_item_img img_logout"></div>
            <div class="nav_item_name">Выйти</div>
        </a>
    </nav>
    <div class="page_right">
        <section class="section_page">
            <a href="//ru.ceramic3d.com/" target="_blank">
                <img class="page_logo" src="{% static 'media/logo.png' %}" alt="logo">
            </a>
            <div class="clear"></div>
            <h1 class="page_title">Реквизиты</h1>
            <div class="kyes_butts">
                <a href="{% url 'main:requisites_add' %}"
                   class="kyes_butts_button kyes_butts_button--orange">Добавить реквизиты</a>
            </div>
            <div class="req">
                {% if not list_req %}
                    <p class="empty">Пока нет реквизитов</p>
                {% else %}
                    {% for req in list_req %}
                        <div class="req_item clearfix" data-hide="{{req.hide}}">
                            <div class="req_item_icon" data-name="{{req.org}}"></div>
                            <div class="req_item_info">
                                <div class="req_item_title">{{req.company}}</div>
                            </div>
                          <div class="req_item_right clearfix">
                                <a href="{% url 'main:ChangeRequisites' pk=req.pk %}" class="req_icon_edit"></a>
                            </div>
                        </div>
                    {% endfor %}
                {%endif%}
            </div>
        </section>
    </div>
</div>
{% endblock %}