Ceramic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bicycle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='')),
]


if settings.DEBUG:
   urlpatterns.append(path('static/<path:path>', never_cache(serve)))
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
   path('', views.loginUser, name='login'),
   path('keys', views.key.as_view(), name="key"),
   path('requisites', views.req.as_view(), name="req"),
   path('logout', views.logout.as_view(), name="logout"),
   path('registration', views.createUser.as_view(), name="createUser"),
   path('validateKey', views.validateKey, name='validateKey'),
   path('password_email/<str:sign>', views.password_email, name='password_email'),
   path('password_email_form', views.password_email_form, name='password_email_form'),
   path('checks', views.checks.as_view(), name="checks"),
   path('help', views.Help.as_view(), name="help"),
   path('profile', views.profile.as_view(), name="profile"),
   path('requisites_add', views.requisites_add.as_view(), name="requisites_add"),
   path('requisites_edit/<int:pk>', views.ChangeRequisites.as_view(), name="ChangeRequisites"),
   path('changePass', views.changePass.as_view(), name="changePass"),
   path('editProfile/<int:pk>', views.ChangeUser.as_view(), name="editProfile"),
]

main/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from datetime import datetime

from .models import AdvUser, keys, helpMessage, requisites, checks


class RegisterUserForm(forms.ModelForm):
    key = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    first_name = forms.CharField()

    def clean_password1(self):
        password = self.cleaned_data['password']
        if password:
            password_validation.validate_password(password)
        return password

    def clean(self):
        super().clean()
        password = self.cleaned_data['password']
        password2 = self.cleaned_data['password2']
        num = self.cleaned_data['key']
        errors = {}
        if keys.objects.filter(number=num, owner='Отсутствует').exists():
            pass
        else:
            errors['key'] = ValidationError(
                'Несуществующий ключ', code='key_errors'
            )
        if password and password2 and password != password2:
            errors['password2'] = ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )
        if errors != '':
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.date = datetime.now()
        user.email = user.username
        key = keys.objects.get(number=user.key, owner='Отсутствует')
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            key.owner = user
            key.save()
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'password', 'password2', 'first_name', 'key')


class loginForm(forms.Form):
    key = forms.CharField(required=False)
    username = forms.EmailField(required=False)
    password = forms.PasswordInput()

    class Meta:
        fields = ('username', 'password', 'key')


class help_form(forms.ModelForm):
    inv = forms.FileField()

    class Meta:
        model = helpMessage
        fields = '__all__'


class add_req_form(forms.ModelForm):
    class Meta:
        model = requisites
        fields = ('org', 'inn', 'kpp', 'company', 'address', 'contacts', 'email', 'phone',
                  'docs', 'bank', 'checking', 'bic', 'checkingCo', 'ogrn', 'type')


class UploadFileForm(forms.ModelForm):
    pk = forms.CharField(required=False)

    class Meta:
        model = checks
        fields = ('pay', 'pk')


class edit_user_form(forms.ModelForm):
    class Meta:
        model = AdvUser
        fields = ('email', 'first_name', 'time', 'phone')

main/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView, PasswordChangeView
from datetime import datetime

from django.core.exceptions import ValidationError
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, TemplateView, UpdateView
from . import forms, models, utilities


def loginUser(request):
    if request.user.is_authenticated:
        return redirect('/keys')
    else:
        context = {'text': 'Войти по ключу', 'key_display': 'none', 'email_display': 'block'}
        if request.method == "POST":
            username = request.POST['username']
            key = request.POST['key']
            password = request.POST['password']

            if key != '':
                context = {'text': 'Войти по email', 'key_display': 'block', 'email_display': 'none'}
                try:
                    key = models.keys.objects.filter(number=key)
                except key.exists():
                    key = models.keys.objects.get(number=key)
                    userBd = models.AdvUser.objects.get(username=key.owner)
                    success = authenticate(username=userBd.username, password=password)
                    if success is None:
                        context['password'] = 'Неверный пароль'
                    else:
                        login(request, success)
                        return redirect('/keys')
                else:
                    context['key'] = 'Несуществующий ключ'
            elif username != '':
                context = {'text': 'Войти по ключу', 'key_display': 'none', 'email_display': 'block'}
                if models.AdvUser.objects.filter(Q(username=username) | Q(email=username)).exists():
                    AdvUser = models.AdvUser.objects.get(Q(username=username) | Q(email=username))
                    success = authenticate(username=AdvUser.username, password=password)
                    if success is None:
                        context['password'] = 'Неверный пароль'
                    else:
                        login(request, success)
                        return redirect('/keys')
                else:
                    context['password'] = 'Неверный пароль'
            else:
                context['username'] = 'Обязательное поле'
                context['key'] = 'Обязательное поле'
        return render(request, 'user/login.html', context)


class logout(LoginRequiredMixin, LogoutView):
    template_name = 'user/logout.html'
    login_url = '/'
    next_page = '/'


class createUser(CreateView):
    model = models.AdvUser
    template_name = 'user/createUser.html'
    form_class = forms.RegisterUserForm
    success_url = '/'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/keys')
        else:
            return render(request, 'user/createUser.html')


class key(LoginRequiredMixin, TemplateView):
    template_name = 'pages/keys.html'
    login_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_keys'] = models.keys.objects.filter(owner=self.request.user.username)
        context['tariffs'] = models.tariffs.objects.all()
        current_time = datetime.now()
        day = current_time.strftime("%d")
        month = int(current_time.strftime("%m")) + 1
        if month // 10 == 0:
            month = f'0{month}'
        year = current_time.strftime("%Y")
        context['first_date'] = f'{day}.{month}.{year}'
        return context

    def post(self, request, *args, **kwargs):
        pk = request.POST['pk']
        name = request.POST['name']
        if name != '':
            keysBd = models.keys.objects.get(pk=pk)
            keysBd.name = name
            keysBd.save()
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)


class req(LoginRequiredMixin, TemplateView):
    template_name = 'pages/req.html'
    login_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_req'] = models.requisites.objects.filter(owner=self.request.user.username)
        return context


class requisites_add(LoginRequiredMixin, CreateView):
    template_name = 'pages/req_add.html'
    success_url = '/requisites_add'
    form_class = forms.add_req_form
    login_url = '/'

    def post(self, request, *args, **kwargs):
        context = {'display': 'none'}
        form = forms.add_req_form(request.POST)
        if form.is_valid():
            context['display'] = 'block'
            instance = form.save(commit=False)
            instance.owner = self.request.user
            if models.requisites.objects.filter(owner=request.user.username).exists():
                instance.type = 'Дополнительный'
            else:
                instance.type = 'Основной'
            instance.save()
        return render(self.request, 'pages/req_add.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['display'] = 'none'
        return context


class ChangeRequisites(LoginRequiredMixin, UpdateView):
    model = models.requisites
    template_name = 'pages/req_edit.html'
    form_class = forms.add_req_form
    success_url = '/requisites'
    login_url = '/'
    pk_url_kwarg = id

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        pk = self.kwargs.get('pk')
        return get_object_or_404(queryset, pk=pk, owner=self.request.user.username)


def validateKey(request):
    context = {}
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.method == 'GET':
            typeQ = request.GET.get('type')
            if typeQ == '1':
                num = request.GET.get('key')
                if models.keys.objects.filter(number=num, owner='Отсутствует').exists():
                    context['success'] = 1
                else:
                    context['success'] = 0
            elif typeQ == '0':
                num = request.GET.get('key')
                check = request.GET.get('check')
                if models.keys.objects.filter(number=num, checkNum=check, owner='Отсутствует').exists():
                    kye = models.keys.objects.get(number=num, checkNum=check)
                    kye.owner = request.user
                    kye.save()
                    context['success'] = 1
                else:
                    context['success'] = 0
            elif typeQ == '2':
                delKeys = request.GET.get('delKeys')
                delKeys = delKeys.split(';')
                context['success'] = delKeys
                for dels in delKeys:
                    context['success'] = dels
                    if dels != '':
                        if models.keys.objects.filter(number=dels).exists():
                            kye = models.keys.objects.get(number=dels)
                            user = models.AdvUser.objects.get(pk=6)
                            kye.owner = user
                            kye.save()
                context['success'] = 1
    return render(request, 'user/validateKey.html', context)


def password_email_form(request):
    if request.user.is_authenticated:
        return redirect('/keys')
    else:
        context = {'display': 'none'}
        if request.method == "POST":
            username = request.POST['username']
            if models.AdvUser.objects.filter(Q(username=username) | Q(email=username)).exists():
                user = models.AdvUser.objects.get(Q(username=username) | Q(email=username))
                utilities.send_password_notification(user)
                context['mail'] = "Проверьте почту"
                context['display'] = 'block'
            else:
                context['errors'] = "Введен неверный логин"
        return render(request, 'user/password_email_form.html', context)


def password_email(request, sign):
    username = utilities.signer.unsign(sign)
    user = get_object_or_404(models.AdvUser, username=username)
    password = utilities.generate_password()
    user.set_password(password)
    user.save()
    context = {'user': username, 'password': password}
    return render(request, 'user/password_change_email.html', context)


class checks(LoginRequiredMixin, CreateView):
    model = models.checks
    form_class = forms.UploadFileForm
    template_name = 'pages/checks.html'
    login_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_checks'] = models.checks.objects.filter(owner=self.request.user.username)
        return context

    def post(self, request, *args, **kwargs):
        context = {'success': 0, 'list_checks': models.checks.objects.filter(owner=request.user.username)}
        form = forms.UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            if models.checks.objects.filter(pk=request.POST['pk'], owner=request.user.username).exists():
                check = models.checks.objects.get(pk=request.POST['pk'], owner=request.user.username)
                check.pay = request.FILES['pay']
                check.save()
            context['success'] = 1

        return render(request, 'pages/checks.html', context)


class Help(LoginRequiredMixin, CreateView):
    template_name = 'pages/help.html'
    success_url = '/help'
    form_class = forms.help_form
    login_url = '/'

    def post(self, request, *args, **kwargs):
        context = {'display': 'none'}
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = self.request.FILES.getlist('inv')
        if form.is_valid():

main/templates/user/changePass.html
{% extends "basic.html" %}
{% load static%}
{% block content %}
<div class="center clearfix">
    <nav class="page_left">
        <a href="{% url 'main:key' %}" class="nav_item clearfix">
            <div class="nav_item_img img_key"></div>
            <div class="nav_item_name">Ключи</div>
        </a>
        <a href="{% url 'main:req' %}" class="nav_item clearfix">
            <div class="nav_item_img img_req"></div>
            <div class="nav_item_name">Реквизиты</div>
        </a>
        <a href="{% url 'main:checks' %}" class="nav_item clearfix">
            <div class="nav_item_img img_rubl"></div>
            <div class="nav_item_name">Счета</div>
        </a>
        <a href="{% url 'main:help' %}" class="nav_item clearfix">
            <div class="nav_item_img img_help"></div>
            <div class="nav_item_name">Помощь</div>
        </a>
        <a href="{% url 'main:profile' %}"  class="nav_item clearfix nav_item--active">
            <div class="nav_item_img img_profile"></div>
            <div class="nav_item_name">Профиль</div>
        </a>
        <a href="{% url 'main:logout' %}" class="nav_item clearfix">
            <div class="nav_item_img img_logout"></div>
            <div class="nav_item_name">Выйти</div>
        </a>
    </nav>
    <div class="page_right">
            <a href="//ru.ceramic3d.com/" target="_blank">
                <img class="page_logo" src="{% static 'media/logo.png' %}" alt="logo">
            </a>
            <div class="clear"></div>
            <h1 class="page_title">Профиль</h1>
        <div class="profileTwo">
            <a href="{% url 'main:profile' %}" class="profileA">Основное</a>
            <a href="{% url 'main:changePass' %}" class="profileA profileA--active">Смена пароля</a>
        </div>
        <div class="clear"></div>
        <form method="post">
                {% csrf_token %}
            <div class="changePinCode">
                <p>Старый пароль</p>
                <label for="password">
                    <input type="password" id="password" name="old_password" class="inputMain" required="">
                    <div class="eye_input"></div>
                    <div class="help_text">{{form.errors.old_password}}</div>
                </label>
            </div>
            <div class="clear"></div>
            <div class="changePinCodeTwo">
                <p>Новый пароль</p>
                <label for="password2">
                    <input type="password" id="password2" name="new_password1" class="inputMain" required="">
                    <div class="eye_input"></div>
                    <div class="help_text">{{form.errors.new_password1}}</div>
                </label>
            </div>
            <div class="clear"></div>
            <div class="changePinCodeThree">
                <p>Повторите пароль</p>
                <label for="password3">
                    <input type="password" id="password3" name="new_password2" class="inputMain" required="">
                    <div class="eye_input"></div>
                    <div class="help_text">{{form.errors.new_password2}}</div>
                </label>
            </div>
            <div class="clear"></div>
            <div class="changePass">
                <input type="submit" class="kyesButBut kyesButButWhite" value="ИЗМЕНИТЬ ПАРОЛЬ">
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/user/createUser.html
{% extends "basic.html" %}
{% load static %}
{% block content %}
<div class="center clearfix">
    <img class="main_left" src="{% static 'media/main_img.png' %}" alt="mainImg">
    <div class="main_right">
        <a href="//ru.ceramic3d.com/" target="_blank">
            <img class="main_logo" src="{% static 'media/logo.png' %}" alt="logo">
        </a>
        <div class="main_right_title">Облачный рендер Ceramic 3D<span>Личный кабинет</span></div>
        <form class="mainForm" method="POST" id="registr">
            {% csrf_token %}
            <div class="two_titles clearfix">
                <div class="form_title">Регистрация</div>
                <a href="/" class="back_butt" id="auth">Авторизоваться</a>
            </div>
            <label for="key">
                <input type="text" id="key" name="key" placeholder="Ключ" class="inputMain" required>
                <div class="help_text">{{form.errors.key}}</div>
            </label>
            <label for="username">
                <input type="email" id="username" name="username" placeholder="Почта" class="inputMain" required>
                <div class="help_text">{{form.errors.username}}</div>
            </label>
            <label for="password">
                <input type="password" id="password" name="password" placeholder="Пароль" class="inputMain" required>
                <div class="eye_input"></div>
                <div class="help_text">{{form.errors.password}}</div>
            </label>
            <label for="password2">
                <input type="password" id="password2" name="password2" placeholder="Повторите пароль" class="inputMain" required>
                <div class="eye_input"></div>
                <div class="help_text">{{form.errors.password2}}</div>
            </label>
            <label for="first_name">
                <input type="text" id="first_name" name="first_name" placeholder="Ф.И.О." class="inputMain" required>
            </label>
            <input type="submit" value="ЗАРЕГИСТРИРОВАТЬСЯ" class="formButt" id="createusBut" disabled>
                <label class="checkbox_container" for="personal">
                    Нажимая на кнопку “Продолжить регистрацию”, я даю согласие на
                    обработку персональных данных и соглашаюсь с условиями
                    <a target="_blank" href="//ru.ceramic3d.com/include/licenses_detail.php">обработки персональных данных</a>
                    <input type="checkbox" name="personal" required id="personal">
                    <span class="checkmark"></span>
                </label>
        </form>
        <div class="contact_text">
            <div class="contact_phone">+7 (495) 215-24-47</div>
            info@ceramic3d.ru<br>
            г. Екатеринбург, проезд<br>
            Решетникова 22а, оф. 410<br>
        </div>
    </div>
</div>
{% endblock %}

main/templates/user/fogotpassword.html
{% extends "basic.html" %}
{% load static %}
{% block content %}

<div class="center clearfix">
    <img class="main_left" src="{% static 'media/main_img.png' %}" alt="mainImg">
    <div class="main_right">
        <a href="//ru.ceramic3d.com/" target="_blank">
            <img class="main_logo" src="{% static 'media/logo.png' %}" alt="logo">
        </a>
        <div class="main_right_title">Облачный рендер Ceramic 3D<span>Личный кабинет</span></div>
        <form class="mainForm" method="POST" id="fogot">
            <div class="two_titles clearfix">
                <div class="form_title">ВОССТАНОВЛЕНИЕ</div>
                <div class="back_butt" id="back">Назад</div>
            </div>
            <label for="login" class="pos">
                <input type="text" name="login" placeholder="Введите почту или ключ" class="inputMain" required>
                <div class="cross_input"></div>
            </label>
            <input type="submit" value="ПОЛУЧИТЬ КОД" class="formButt">
        </form>
        <div class="contact_text">
            <div class="contact_phone">+7 (495) 215-24-47</div>
            info@ceramic3d.ru<br>
            г. Екатеринбург, проезд<br>
            Решетникова 22а, оф. 410<br>
        </div>
    </div>
</div>
{% endblock %}

main/templates/user/password_change_email.html
{% extends "basic.html" %}
{% load static%}
{% block content %}
<div class="dark_errors" style="display: block;">
   <div class="errors_container errors_container--email" style="display: block;">
        <div class="errors_container_titles clearfix">
            <div class="errors_container_title">Ceramic 3D</div>
        </div>
        <div class="password_success">
            <div class="title">Здравствуйте, {{user}}!</div>
            <p class="new_pass">Ваш новый пароль: <span>{{password}}</span>
            <p class="help_pass">Администрация сайта настоятельно рекомендует сменить его на более
                                 надежный и удобный.</p>
        </div>
        <a href="{% url 'main:login' %}" class="errors_container_butt key_add_butt">АВТОРИЗАЦИЯ</a>
   </div>
</div>
{% endblock %}

main/templates/user/user_edit.html
{% extends "basic.html" %}
{% load static%}
{% block content %}
<div class="center clearfix">
    <nav class="page_left">
        <a href="{% url 'main:key' %}" class="nav_item clearfix">
            <div class="nav_item_img img_key"></div>
            <div class="nav_item_name">Ключи</div>
        </a>
        <a href="{% url 'main:req' %}" class="nav_item clearfix">
            <div class="nav_item_img img_req"></div>
            <div class="nav_item_name">Реквизиты</div>
        </a>
        <a href="{% url 'main:checks' %}" class="nav_item clearfix">
            <div class="nav_item_img img_rubl"></div>
            <div class="nav_item_name">Счета</div>
        </a>
        <a href="{% url 'main:help' %}" class="nav_item clearfix">
            <div class="nav_item_img img_help"></div>
            <div class="nav_item_name">Помощь</div>
        </a>
        <a href="{% url 'main:profile' %}"  class="nav_item clearfix nav_item--active">
            <div class="nav_item_img img_profile"></div>
            <div class="nav_item_name">Профиль</div>
        </a>
        <a href="{% url 'main:logout' %}" class="nav_item clearfix">
            <div class="nav_item_img img_logout"></div>
            <div class="nav_item_name">Выйти</div>
        </a>
    </nav>
    <div class="page_right">
        <a href="//ru.ceramic3d.com/" target="_blank">
            <img class="page_logo" src="{% static 'media/logo.png' %}" alt="logo">
        </a>
            <div class="clear"></div>
            <h1 class="page_title">Изменение профиля</h1>
        <div class="clear"></div>
        <form method="post" class="prof_edit_form">
                {% csrf_token %}
            <div class="changePinCode">
                <p>Контактная почта</p>
                <label for="email2">
                    <input type="email" id="email2" name="email" class="inputMain" required value="{{form.email.value}}">
                    <div class="help_text">{{form.errors.email}}</div>
                </label>
            </div>
            <div class="clear"></div>
            <div class="changePinCode">
                <p>Имя пользователя</p>
                <label for="first_name">
                    <input type="text" id="first_name" name="first_name" class="inputMain" required value="{{form.first_name.value}}">
                    <div class="help_text">{{form.errors.first_name}}</div>
                </label>
            </div>
            <div class="clear"></div>
             <div class="changePinCode">
                <p>Номер телефона</p>
                <label for="phone2">
                    <input type="text" id="phone2" name="phone" class="inputMain" required value="{{form.phone.value}}">
                    <div class="help_text">{{form.errors.phone}}</div>
                </label>
            </div>
            <div class="clear"></div>
            <div class="changePinCode">
                <p>Часовой пояс</p>
                <label for="time">
                    <select class="profile_select" data-value="{{form.time.value}}" name="time" id="time">
                        <option value="GMT -12">(GMT -12:00) Эниветок, Кваджалейн </option>
                        <option value="GMT -11">(GMT -11:00) Остров Мидуэй, Самоа </option>
                        <option value="GMT -10">(GMT -10:00) Гавайи </option>
                        <option value="GMT -9">(GMT -9:00) Аляска </option>
                        <option value="GMT -8">(GMT -8:00) Тихоокеанское время (США и Канада) </option>
                        <option value="GMT -7">(GMT -7:00) Горное время (США и Канада) </option>
                        <option value="GMT -6">(GMT -6:00) Центральное время (США и Канада), Мехико</option>
                        <option value="GMT -5">(GMT -5:00) Восточное время (США и Канада), Богота, Лима </option>
                        <option value="GMT -4">(GMT -4:00) Атлантическое время (Канада), Каракас, Ла-Пас </option>
                        <option value="GMT -3:30">(GMT -3:30) Ньюфаундленд </option>
                        <option value="GMT -3">(GMT -3:00) Бразилия, Буэнос-Айрес, Джорджтаун </option>
                        <option value="GMT -2">(GMT -2:00) Срединно-Атлантического </option>
                        <option value="GMT -1">(GMT -1:00) Азорские острова, острова Зеленого Мыса </option>
                        <option value="GMT 0">(GMT 0:0) Время Западной Европе, Лондон, Лиссабон, Касабланка </option>
                        <option value="GMT +1">(GMT +1:00) Брюссель, Копенгаген, Мадрид, Париж </option>
                        <option value="GMT +2">(GMT +2:00) Киев, Калининград, Южная Африка </option>
                        <option value="GMT +3">(GMT +3:00) Багдад, Эр-Рияд, Москва, Санкт-Петербург</option>
                        <option value="GMT +3:30">(GMT +3:30) Тегеран </option>
                        <option value="GMT +4">(GMT +4:00) Абу-Даби, Мускат, Баку, Тбилиси</option>
                        <option value="GMT +4:30">(GMT +4:30) Кабул </option>
                        <option value="GMT +5">(GMT +5:00) Екатеринбург, Исламабад, Карачи, Ташкент</option>
                        <option value="GMT +5:30">(GMT +5:30) Бомбей, Калькутта, Мадрас, Нью-Дели</option>
                        <option value="GMT +5:45">(GMT +5:45) Катманду</option>
                        <option value="GMT +6">(GMT +6:00) Алматы, Дакке, Коломбо </option>
                        <option value="GMT +7">(GMT +7:00) Бангкок, Ханой, Джакарта</option>
                        <option value="GMT +8">(GMT +8:00) Пекин, Перт, Сингапур, Гонконг</option>
                        <option value="GMT +9">(GMT +9:00) Токио, Сеул, Осака, Саппоро, Якутск</option>
                        <option value="GMT +9:30">(GMT +9:30) Аделаида, Дарвин </option>
                        <option value="GMT +10">(GMT +10:00) Восточная Австралия, Гуам, Владивосток </option>
                        <option value="GMT +11">(GMT +11:00) Магадан, Соломоновы острова, Новая Каледония</option>
                        <option value="GMT +12">(GMT +12:00) Окленд, Веллингтон, Фиджи, Камчатка</option>
                    </select>
                    <div class="help_text">{{form.errors.phone}}</div>
                </label>
            </div>
            <div class="clear"></div>
            <div class="changePass">
                <input type="submit" class="kyesButBut kyesButButWhite" value="ИЗМЕНИТЬ">
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/user/validateKey.html
{{success}}